name: LaTeX

on:
    push:
        branches: [ main ]

jobs:
    compile:
        name: "Compile source files"
        runs-on: ubuntu-latest
        env:
            SRC: slides
            PDF: slides.pdf

        steps:
          - name: "Checkout sources"
            uses: actions/checkout@v3

          - name: "Install TeX distribution"
            run: |
                sudo apt-get update
                sudo apt-get install texlive texlive-bibtex-extra texlive-fonts-extra texlive-latex-extra texlive-publishers texlive-science texlive-xetex
                sudo apt-get install biber

          - name: "Compile LaTeX"
            working-directory: .
            run: |
                xelatex -interaction nonstopmode -halt-on-error -file-line-error -shell-escape ${{ env.SRC }}
                biber ${{ env.SRC }}
                xelatex -interaction nonstopmode -halt-on-error -file-line-error -shell-escape ${{ env.SRC }}
                xelatex -interaction nonstopmode -halt-on-error -file-line-error -shell-escape ${{ env.SRC }}

          - name: "Prepare artifacts directory"
            run: mkdir -p artifacts && mv ${{ env.PDF }} ./artifacts/

          - name: "Upload artifacts"
            uses: actions/upload-artifact@v3
            with:
                name: ${{ env.PDF }}
                path: ./artifacts

    deploy:
        name: "Deploy PDF to GitHub Pages"
        needs: [compile]
        runs-on: ubuntu-latest

        steps:
          - name: "Checkout sources"
            uses: actions/checkout@v3

          - name: "Download artifacts"
            uses: actions/download-artifact@v3
            with:
                path: artifacts

          - name: "Prepare deployment directory"
            run: mkdir -p deploy && mv artifacts/*/* deploy

          - name: "Deploy to branch"
            uses: peaceiris/actions-gh-pages@v3
            with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./deploy
                publish_branch: gh-pages
                force_orphan: true
