name: LaTeX

on:
    push:
        branches: [ main ]

jobs:
    compile:
        name: "Compile source files"
        runs-on: ubuntu-latest
        env:
            TEXFILE: slides

        steps:
          - name: "Checkout sources"
            uses: actions/checkout@v3

          - name: "Install TeX distribution"
            run: |
                sudo apt-get update
                sudo apt-get install texlive texlive-publishers texlive-science latexmk cm-super

          - name: "Compile LaTeX"
            working-directory: .
            run: |
                pdflatex ${{ env.TEXFILE }}
                bibtex ${{ env.TEXFILE }}
                pdflatex ${{ env.TEXFILE }}
                pdflatex ${{ env.TEXFILE }}

          - name: "Prepare artifacts directory"
            run: mkdir -p artifacts && mv ${{ env.TEXFILE }}.pdf ./artifacts/

          - name: "Upload artifacts"
            uses: actions/upload-artifact@v3
            with:
                name: ${{ env.TEXFILE }}.pdf
                path: ./artifacts

    deploy:
        needs: [compile]
        runs-on: ubuntu-latest

        steps:
          - name: "Checkout sources"
            uses: actions/checkout@v3

          - name: "Download artifacts"
            uses: actions/download-artifact@v3
            with:
                path: artifacts

          - name: "Prepare deployment directory"
            run: mkdir -p deploy && mv artifacts/*/* deploy

          - name: "Deploy to branch"
            uses: peaceiris/actions-gh-pages@v3
            with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./deploy
                publish_branch: latex
                force_orphan: true
